dist: xenial

services:
  - mongodb

language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n daisy python=$TRAVIS_PYTHON_VERSION
  - source activate daisy

install:
  - make
  - make install-dev

script:
  - make tests
